name: zeerah
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.2
  flutter_card_swiper: ^7.2.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.1
  provider: ^6.1.5+1
  intl: ^0.20.1
  geocoding: ^4.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  card_swiper: ^3.0.1
flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/splash_screen.webp
    - lib/assets/images/sign_in.webp
    - lib/assets/images/google_sign.webp
    - lib/assets/images/mail_signin.webp
    - lib/assets/images/otp_verifly.webp
    - lib/assets/images/appliance_repair.webp
    - lib/assets/images/cleaning.webp
    - lib/assets/images/electrician.webp
    - lib/assets/images/home_page_banner.png
    - lib/assets/images/home_page_calender.webp
    - lib/assets/images/home_page_gardering.webp
    - lib/assets/images/home_page_gift_box.webp
    - lib/assets/images/home_page_location.webp
    - lib/assets/images/home_page_notifications.webp
    - lib/assets/images/home_page_parse.webp
    - lib/assets/images/pest_control.webp
    - lib/assets/images/plumber.webp
    - lib/assets/images/homepage_background_banner.webp
    - lib/assets/images/home_page_appbar_coin.webp
    - lib/assets/images/homepage_banner_dummy_image.png
    - lib/assets/images/homepage_banner_dummy_image2.png
    - lib/assets/images/homepage_banner_dummy_image3.png
    - lib/assets/images/explore_category1.png
    - lib/assets/images/explore_category2.png
    - lib/assets/images/explore_category3.png
    - lib/assets/images/explore_category4.png
    - lib/assets/images/trustful_section_image1.webp
    - lib/assets/images/trustful_section_image2.webp
    - lib/assets/images/trustful_section_image3.webp
    - lib/assets/images/refer_section.webp
    # cleaning
    - lib/assets/images/cleaning_bathroom.png
    - lib/assets/images/cleaning_full_house.png
    - lib/assets/images/cleaning_kitchan.png
    - lib/assets/images/cleaning_living_room.png
    # electrical
    - lib/assets/images/electrical_fan.png
    - lib/assets/images/electrical_swicth.png
    - lib/assets/images/electrical_wireing.png
    - lib/assets/images/electrical_inverter.png
    - lib/assets/images/electrical_light.png
    - lib/assets/images/electrical_doorbell.png
    - lib/assets/images/electrical_appliences.png
    - lib/assets/images/electrical_book_consulting.png
    # pest control
    - lib/assets/images/cockroach_control.png
    - lib/assets/images/beg_bugs_control.png
    - lib/assets/images/termite_control.png
    - lib/assets/images/rider_car.png
    - lib/assets/images/car.png
    - lib/assets/images/handsman.png
    - lib/assets/images/worker_1.png
    - lib/assets/images/worker_2.png
    - lib/assets/images/rider_image.png
    - lib/assets/images/man.png

    #Service booking

    - lib/assets/images/service_booking_dummy_image1.webp
    - lib/assets/images/service_booking_dummy_image2.webp
    - lib/assets/images/service_booking_dummy_image3.webp
    - lib/assets/images/bookings__coins.png

    #service progress
    - lib/assets/images/service_in_progress_image.jpeg
    - lib/assets/images/service_completed.png
    - lib/assets/images/progress_clock.png

    #payments images
    - lib/assets/images/payments_cash_on_delivery.png
    - lib/assets/images/payments_credit_card.png
    - lib/assets/images/payments_selceted.png
    - lib/assets/images/payments_upi.png
    - lib/assets/images/payments_wallet.png
    - lib/assets/images/bookings.png

  fonts:
  - family: Inter
    fonts:
      - asset: lib/assets/fonts/Inter-Light.ttf
        weight: 300
      - asset: lib/assets/fonts/Inter-Medium.ttf
        weight: 500
      - asset: lib/assets/fonts/Inter-SemiBold.ttf
        weight: 600
      - asset: lib/assets/fonts/Inter-Bold.ttf
        weight: 700