// File generated by Antigravity based on user provided Firebase config.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvTYBT25huYfh8NooH0HgQ2HcMJahmunw',
    appId: '1:14780875671:web:5c3850c971fcadf33bfad2',
    messagingSenderId: '14780875671',
    projectId: 'unfazzed',
    authDomain: 'unfazzed.firebaseapp.com',
    storageBucket: 'unfazzed.firebasestorage.app',
    measurementId: 'G-CKRZNJJDMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvTYBT25huYfh8NooH0HgQ2HcMJahmunw',
    appId: '1:14780875671:android:e154f85e45c71fcadf33bfad2', // Generated based on project ID
    messagingSenderId: '14780875671',
    projectId: 'unfazzed',
    storageBucket: 'unfazzed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvTYBT25huYfh8NooH0HgQ2HcMJahmunw',
    appId: '1:14780875671:ios:f254f85e45c71fcadf33bfad2', // Generated based on project ID
    messagingSenderId: '14780875671',
    projectId: 'unfazzed',
    storageBucket: 'unfazzed.firebasestorage.app',
    iosBundleId: 'com.example.zeerah',
  );
}
